services:
  app:
    image: baeaubab:v1
    container_name: baeaubab_v1
    networks:
      - default
    ports:
      - "3500:3000"

volumes:
  app-data:

networks:
  bridge-baeaubab:
    external: true
