import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/queryProviders";
import { Toaster } from "@/components/ui/sonner";
import ProgressBar from "@/components/progressBar";
import NextTopLoader from 'nextjs-toploader';
import { Montserrat, Roboto } from "@next/font/google"

const montserrat = Montserrat()

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen w-full ${montserrat.className} items-center justify-center antialiased bg-[#101010] `}
      >
        <NextTopLoader speed={5000} />
        <Providers>{children}</Providers>
        <Toaster duration={3000} position="top-right" expand={true} />
      </body>
    </html>
  );
}
