version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      bridge-baeaubab:
        ipv4_address: 172.30.0.10
      default: {}

  worker_3:
    restart: on-failure
    build:
      context: .
      dockerfile: worker_3/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    networks:
      bridge-baeaubab: {}
      default: {}

  worker_4:
    restart: on-failure
    build:
      context: .
      dockerfile: worker_4/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    networks:
      bridge-baeaubab: {}
      default: {}

networks:
  bridge-baeaubab:
    external: true
